name = "cf_ai_worker_agent"
main = "src/worker.ts"
compatibility_date = "2024-11-20"


ai = { binding = "AI", remote = true }
[[vectorize]]
binding   = "DOC_INDEX"
index_name = "cf-ai-index"
  



[durable_objects]
bindings = [
  { name = "CHAT_AGENT", class_name = "ChatAgent", script_name = "chat-agent-worker" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatAgent"]

[vars]
MODEL = "@cf/meta/llama-3.3-8b-instruct"
MEMORY_MAX_MESSAGES = 24

[assets]
directory = "./public"
